### ISSUE TITLE
Xcode terminal doesn't support color

### ISSUE THREAD

**Issue by kastiglione** [dduan/Dye#7]
Xcode's terminal doesn't support the color escape sequences. Not sure what you want to do, but here's the details.

When running this code from Xcode:

```swift
stream.write(
    ("Hello, ", []),
    ("world", [.foreground(.red), .style(.bold)])
)
```

The output visually appears as:

```
[0m[0m[0mHello, [38;5;1;1mworld[0m!
```

When pasting it to the terminal it shows:

```
^[[0m^[[0m^[[0mHello, ^[[38;5;1;1mworld^[[0m!
```

**Comment by dduan** [comment]
Xcode reports it self as a tty. This is a known Xcode bug.
